# -*- coding: utf-8 -*-
"""PyLadies Meydan Okuma v0.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cn2tm_jH0GjFs7RlX0hnafuGQMI3RDOD

Merhaba PyLadies Ankara!

Meydan okuma görevinize hoşgeldiniz!

Toplam süre 8 saat olacaktır ve dış kaynakalardan alınan kodlar kabul edilmemektedir.

[Amiral Battı](https://tr.wikipedia.org/wiki/Amiral_battı_(oyun)) ve [Mayın Tarlası](https://tr.wikipedia.org/wiki/Mayın_Tarlası) benzeri küçük bir masa oyunu yapacağız.

Öncelikle oyun haritamızı tanıyalım.

![map.jpeg](https://i.hizliresim.com/0jciDX.png)


0-99 arası rastgele seçilecek hedef noktamızı tahminler yaparak bulmaya çalışacağız.

Yapılan tahmin eğer doğru ise "ISABET!" 

Yapılan tahmin eğer 3 blok çevresinde ise "SICAK!" 

Yapılan tahmin eğer daha uzak ise "SOGUK!" 

(BONUS) Çıktısı verecek ve muhtemel çevresini işaretleyerek (renk ve ya bold italik  kullanabilirsiniz) geri bildirim yapacak. 

Katılan arkadaşlara başarılar diliyorum

Unutmayın amaç eğlenmek ve öğrenmek kimse yapamadınız diye sizi eleştirmeyecek :)

Batuhan Ilıkan
"""

# burayı değiştirmeyin.
import random
secret=random.randint(0, 100)
# burayı değiştirmeyin.

"""Random sayıyı bu bloğu çalıştırarak değiştirebilirsiniz.

# Task 1

**Oyun Haritasını Oluşturma**

10x10 bir matris oluşturarak yazdırmanız bekleniyor.
"""



"""# Task 2

**Tahmin Alma**

Klavyeden girdi alıp *n* sayısı olarak tutun.

"Tahmin : " olarak aldığınız sayı eğer 0-99 arasında değilse

 "Lütfen 0-99 arasında bir sayı giriniz!" yazdırın.
"""



"""# Task 3

**Tahmin Değerinin Yakınlığını Hesaplama**

2 boyutlu bir düzlemde çalıştığımız için 3 blok çevresi yalnızca -+3 olarak alınmıyor. 

Örneğin 45 sayısının 3 blok çevresindeki sayılar 15, 24-26, 33-37, 42-48, 53-57, 64-66, 75 

![map.jpeg](https://i.hizliresim.com/bj5feU.png)

Bu bağlamda yöntem geliştirmeniz bekleniyor. Eğer bu adımda sıkıntı yaşarsanız discord üzerinden yardım isteyebilirsiniz. Önceliğiniz kendiniz çözmek olmalı ama :)

Bu örnekte 45 sayısı kullanıcıdan aldığımız *n* değeri olsun.

Kodumuzun bizim için oluşturduğu *secret* değeri 66 ise;

**66**->65->55->45

Gördüğünüz gibi 3 adımda erişebiliyoruz.Yani almamız gerken çıktı "SICAK!" olacak

Burda Sonuç olarak bize bir *cevap* gelmesini istiyoruz.

1.   Yapılan tahmin eğer doğru ise "ISABET!"
2.   Yapılan tahmin eğer 3 blok çevresinde ise "SICAK!"
3.   Yapılan tahmin eğer daha uzak ise "SOGUK!"


"""

# burayı değiştirmeyin.
cevap = ""
# burayı değiştirmeyin.



"""# Task 4(BONUS)

//  **Yapmak Zorunlu Değildir!**  //

**Görsel Eklemeler**

Task 3'de eklediğim harita resmine benzer bir çıktı almanızı bekliyorum.

Varsayalım ki 45 değerini seçtik ve bize sıcak olduğunu döndü.

45 değerinin doğru olmadığını bildiğimiz için artık o değeri haritadan kaldırabiliriz. 

Etrafındaki 3 birimlik alanda olabildiğini anladığımız için renklendirerek farkındalık kazandırabiliriz.

Eğer soğuk olsaydı bu sefer 45 ve etrafındaki 3 birimlik alan doğru olmayacağı için onları silebiliriz.

Bu sayede oyunumuz daha anlaşılabilir ve güzel olacaktır.

"""



"""# Final Task

**Hadi Çalıştıralım**

Daha önce yazdığımız kodları kullanarak sayıyı bulana kadar dönecek ve her seferinde yeni tahmin isteyecek kodu yazmanız bekleniyor.


"""

